name: login
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  carousel: ^0.1.0
  cupertino_icons: ^0.1.0
  material_search: ^0.2.7
  camera: ^0.2.1
  sqflite: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/eva.png
    - assets/fern.png
    - assets/landscape.png
    - assets/forrest.png
    - assets/blueforrest.png
    - assets/smallfern.png
    - assets/weirdplant.png
    - assets/leaf.png
    - assets/image1.jpg
    - assets/image2.jpg
    - assets/image3.jpg
    - assets/image4.jpg
    - assets/image5.jpg
    - assets/image6.jpg
    - assets/image7.jpg
    - assets/image8.jpg
    - assets/image9.jpg
    - assets/image10.jpg
    - assets/image11.png
    - assets/image12.png
    - assets/image13.png
    - assets/logowithouteva.png
    - assets/example.db

  fonts:
    - family: Potra
      fonts:
        - asset: assets/Potra.ttf
